### ISSUE TITLE
语料库的课后资料汇集

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/NotThatCS#2]
下下周（下周国庆放假）讲解内容：搜索引擎

讨论内容（可能包括，但不限于下面的问题）：
        新时代对语料库的需求变化？（新算法的影响）
        （大数据）时代下，语料库如何收集和处理？
        有哪些问题，有什么解决方案？

**Comment by morning-ding** [comment]
我在这里简要谈一下舆情监测语料库的建立方法和应用。
通过建立动态舆情监测语料库，提供可供检索的关 键词数据库，结合修辞学、语言学的分析方法，分析舆论 话语表达、公众社会关系、群体心理特征等。首先按照一 定的规则和专题对收集的舆情文本内容进行分类和标注， 然后是文本合并和关键词提取。在语料处理方面要注意两 点：一是小型基础语料库的支撑和建设，大数据库作为信息母体，需要若干小型数据库作为检索源；二是中心度和 关联度结构化的算法，大数据库作为一种非结构化的数 据，需要进行一些结构化的解读和梳理，这就需要相关的 数据结构化算法，这种算法可称之为数据模型。
1．舆情热词语料库。舆情热词语料库主要服务于舆 情监测，解决重大和突发事件中引爆点和关联度的关系。 我们可以通过关注热点内容，搜集热点事件的语料，建立 舆情热词数据库，找出引发舆情关注的引爆词。并结合语 词情感分析、修辞分析手段，来划分引爆词的中心度级别 和关联度级别，在此基础上设计热词发现模型，达到舆情 预警和预测的目的。 
首先我们根据研究规模来选取一定数量的样本，然后 用语料库构建工具对选定文本进行标注和结构化处理， 对舆情关键词进行再次统计并生成核心主题词表数据 库，从中找出舆情引爆词。需要特别指出一点，核心主 题词不一定是词频最高的那个词，而是舆情敏感度，也 就是热度最高的词，即舆论的中心词。中心词是舆论的 引爆点，实现了引导公众把舆论由说变成做的过程，同 时也是关联度最高的词，从最大限度上关联其他的主题 词并形成语义网络。
关于舆情热词的分析，有两个关键点：引爆点和关联点。由引爆点可以导出对引爆词的挖掘；由关联点可以导 出对连接词的发现；引爆词具有意见领袖的作用，迅速扩 大热词的影响力并号召公众付之行动；关联词具有搬运工 的作用，能够连接各种关系词，形成主题词网络。基于引 爆词的挖掘和连接词的发现，舆情热词分析可以划分出两 个维度：中心度分析和关联度分析，进而设定中心度指标 和关联度指标，并设计指标体系的计算公式，形成具有引 爆性质的热词理论模型。这样就可以舆情监测，随着热词 强度的提高，热词的范围是不是在扩大，社会的紧张度又 如何，进而往前预推，达到预警的目的。
2．意见领袖修辞特征词语料库。在一些官方传统媒 体失语或报道不及时的情况下，网民习惯于打开网络意见 领袖的博客或追逐微博上的只言片语，从他们那里寻找解 读、剖析和批判。意见领袖的观点、意见情绪能为受众所 接收，能引起受众的共鸣，会产生巨大的舆论影响，这与 他们个人的话语表达风格、对某个领域的专业知识和对某 类问题的把握能力密不可分。因此，通过对意见领袖的观 点、态度关键主题词等内容的提取，可以从中总结某个或 某类意见领袖的修辞特点及个人特征，形成一定的辨识度 依据；进而还可以从中寻找具有心理唤起度和社会动员能 力的词，为舆论引导提供来自民间舆论场的参照。
3．传播学学术主题词语料库。在传播学内容研究 领域，可以尝试用语料库来完成对常规5W领域的深化研 究，尤其是引向微观层面。越是细小的不易觉察的，越是 人们忽视的，也越是研究者值得进军的领域，而微观的研 究恰恰能够揭示很多深度的东西。所以传播学主题词语料 库可以做的，恰恰是把非结构化的文本数据结构化，根据 研究主题设定结构化的方向、结构化的坐标、结构化的指 标，来完成研究的目标。比如传播史方面的研究，我们可 以找到一个时间节点，搜集与这一节点同步的史实资料， 然后把文本进行整合、分词、标注，提取与这一历史节点 关联的年份词、学者名称、学术观点、专门术语，构建主 题词语料库，绘制这一时期的主题词学术地图。
4．受众特征关键词语料库。利用微博进行广告传 播，有着天然的精准投放优势。我们可以利用语料库来分 析挖掘受众群体特征，绘制不同目标群体的心理图谱、行 为图谱和社会图谱，从而实现对目标接触点的精准把握， 找到受众的需求交叉点。这种语料库分析的应用原理来自 于特征聚类，以此为依据，来向具有相似心理需求的受众 推送受本群体认可的资讯和产品广告，从而达到对品牌接 触点和受众需求交叉点的精准把握。

**Comment by mayinghua** [comment]
请大家注意，如果内容是引用，

1，请使用公开渠道的文献；
2，给出引用信息；
3，请务必理解所引用的内容，并可以回答相关问题。

最后，还请将内容合并到corpus.md文档中。谢谢！
